name: Stride
options:
  bundleIdPrefix: com.preetanshumishra
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "16.0"
settings:
  SWIFT_VERSION: "6.0"
  GENERATE_INFOPLIST_FILE: false
targets:
  Stride:
    type: application
    platform: iOS
    sources:
      - path: Stride
    settings:
      INFOPLIST_FILE: Stride/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.preetanshumishra.stride
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      SWIFT_STRICT_CONCURRENCY: complete
